server:
  port: 5001

db:
  type: 'mysql'
  port: 3306

jwt:
  represh_expiresIn: 3600 * 1000 * s
  access_expiresIn: 600 * 1000 * s

flask:
  port: 5000
  username: 'guru_back_server'
  password: 'back!Password123!'

redis:
  url: '127.0.0.1'
